image: atlassian/default-image:2
pipelines:
  default:
    - step:
        script:
          - curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
          - curl -L https://raw.githubusercontent.com/docker/compose/1.18.0/contrib/completion/bash/docker-compose -o /etc/bash_completion.d/docker-compose
          - chmod +x /usr/local/bin/docker-compose
          - docker-compose -v
          - bash -c "./cx env init --yes --skip-source"
          - bash -c "./cx wb test"
          - bash -c "./cx env down"
        services:
          - docker
