<?php

/**
 * UserAttributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
namespace Cx\Core\User\Model\Repository;

/**
 * UserAttributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAttributeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Find all User Attributes without a parent
     *
     * @return array all attributes without a parent
     */
    public function findAllWithoutParent()
    {
        $qb = $this->createQueryBuilder('a');
        $qb->leftJoin('a.parent', 'p');
        $qb->where($qb->expr()->isNull('p.id'));

        return $qb->getQuery()->getResult();
    }
}