<?php

/**
 * UserAttributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
namespace Cx\Core\User\Model\Repository;

/**
 * UserAttributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAttributeRepository extends \Doctrine\ORM\EntityRepository
{

}