options:
  -
    name: secondary_color
    specific:
      color: '#E5E5E5'
  -
    name: font_color
    specific:
      color: '#575756'
  -
    name: regular_text  
    specific:
      activeChoice: 'Lato'
  -
    name: title_text  
    specific:
      activeChoice: 'Lato'
  -
    name: logo
    specific:
      url: /themes/graham/images/logo.png
    type: Cx\Core_Modules\TemplateEditor\Model\Entity\ImageOption
    translation:
        1: logo
        2: logo
  -
    name: home_images
    specific:
      urls:
        1: /themes/graham/images/img1.jpg
        2: /themes/graham/images/img2.jpg
        3: /themes/graham/images/img3.jpg
        4: /themes/graham/images/img4.jpg
        5: /themes/graham/images/img5.jpg
        6: /themes/graham/images/img6.jpg
        7: /themes/graham/images/img7.jpg
        8: /themes/graham/images/img8.jpg
    type: Cx\Core_Modules\TemplateEditor\Model\Entity\ImageSeriesOption
    translation:
      1: 'Bilder Startseite'
      2: 'Homepage Images'